package com.ssg.dsilbackend.dto;

public enum FacilityName {
    PARKING_AVAILABLE,
    VALET_AVAILABLE,
    CORKAGE_FREE,
    CORKAGE_AVAILABLE,
    WELCOME_KIDS_ZONE,
    NO_KIDS_ZONE,
    RENTAL_AVAILABLE,
    SOMMELIER_AVAILABLE,
    DISABLED_FACILITIES_AVAILABLE,
    PET_FRIENDLY,
    FREE_WIFI_AVAILABLE,
    SMOKING_ZONE
}
